export const productsJSON = [
  {
    id: '1',
    src: "https://assets.pokemon.com/assets/cms2-es-es/img/cards/web/SWSH11/SWSH11_ES_TG10.png",
    name: "Snorlax",
    description: "Carta Snorlax",
    price: "100",
    category_id: "1",
  },
  {
    id: '2',
    src: "https://assets.pokemon.com/assets/cms2-es-es/img/cards/web/SM5/SM5_ES_31.png",
    name: "Piplup",
    description: "Carta Piplup",
    price: "200",
    category_id: "1",
  },
  {
    id: '3',
    src: "https://assets.pokemon.com/assets/cms2-es-es/img/cards/web/SWSHP/SWSHP_ES_SWSH050.png",
    name: "Charizard",
    description: "Carta Charizard",
    price: "300",
    category_id: "1",
  },
  {
    id: '4',
    src: "https://assets.pokemon.com/assets/cms2-es-es/img/cards/web/SM8/SM8_ES_5.png",
    name: "Chikorita",
    description: "Carta Chikorita",
    price: "400",
    category_id: "1",
  },
  {
    id: '5',
    src: "https://assets.pokemon.com/assets/cms2-es-es/img/cards/web/SWSH11/SWSH11_ES_88.png",
    name: "Machamp",
    description: "Carta Machamp",
    price: "500",
    category_id: "1",
  },
  {
    id: '6',
    src: "https://assets.pokemon.com/assets/cms2-es-es/img/cards/web/BWP/BWP_ES_BW89.png",
    name: "Vaporeon",
    description: "Carta Vaporeon",
    price: "500",
    category_id: "1",
  },
  {
    id: '7',
    src: "https://www.pokemoncenter.com/products/images/P8432/741-95065/P8432_741-95065_01_full.jpg",
    name: "Polo",
    description: "Eevee Pokémon Nature: Fall Black Heavyweight Crop Long-Sleeve Shirt - Women",
    price: "29.99",
    category_id: "2",
  },
  {
    id: '8',
    src: "https://www.pokemoncenter.com/products/images/P8432/741-95030/P8432_741-95030_01_full.jpg",
    name: "Polera",
    description: "Mushroom Forest Pokémon Nature: Fall Charcoal Relaxed Fit Zip-Up Hoodie - Adult",
    price: "49.99",
    category_id: "2",
  },
  {
    id: '9',
    src: "https://www.pokemoncenter.com/products/images/P8432/741-95105/P8432_741-95105_01_full.jpg",
    name: "Polo",
    description: "Treehouse Friends Pokémon Nature: Fall Green Relaxed Fit Crew Neck T-Shirt - Adult",
    price: "24.99",
    category_id: "2",
  },
];
